steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dev-healthcare-backend', './backend/healthcare']

#  # Push the container image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/$PROJECT_ID/dev-healthcare-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
          'run',
          'deploy',
          'dev-healthcare-backend',
          '--image',
          'gcr.io/$PROJECT_ID/dev-healthcare-backend',
          '--region',
          'asia-southeast1',
          '--platform',
          'managed',
          '--allow-unauthenticated',
      ]
#images:
#  - gcr.io/$PROJECT_ID/dev-healthcare-backend