version: "3.8"

services:
#  backend:
#    container_name: healthcare-backend
#    image: node:12-alpine
#    command: sh -c 'cd server && yarn && yarn start:dev'
#    ports:
#      - "3000:3000"
#    expose:
#      - 3000
#    volumes:
#      - .:/server
#    env_file:
#      - .env
#    environment:
#      NODE_ENV: development
#      DB_HOST: db
#      DB_USERNAME: root
#      DB_PASSWORD: root-dev
#    depends_on:
#      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'healthcare'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user-dev'
      MYSQL_ROOT_PASSWORD: 'root-dev'
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - dev-db:/var/lib/mysql

volumes:
  dev-db: